blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions ğŸ’¬
    url: https://github.com/SamErde/PSPreworkout/discussions
    about: Please use GitHub discussions for any questions.
  - name: Documentation ğŸ“š
    url: https://day3bits.com/PSPreworkout
    about: Documentation for the PSPreworkout project.
  - name: ReadTheDocs ğŸ“– (Alternate/Backup Documentation Site)
    url: https://pspreworkout.readthedocs.io/en/latest/
    about: ReadTheDocs for the PSPreworkout project.
#  - name: Basic FAQs â“
#    url: https://github.com/SamErde/PSPreworkout/wiki/FAQs
#    about: Answers to the Basic Frequently Asked Questions
